In [1]:
import numpy as np

作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [28]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
with open('hw.npz', 'wb') as f:
    np.savez(f,array1,array2)

In [46]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
npzfile = np.load('hw.npz')
print(npzfile['arr_0'])
print(npzfile['arr_1'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [48]:
#讀取並加入multi_array.npz
npzmulti = np.load('multi_array.npz')
npzmulti.files
with open('hw.npz', 'wb') as f:
    np.savez(f,array1,array2,npzmulti['array1'],npzmulti['array2'],npzmulti['array3'])
#試讀取一次
array = np.load('hw.npz')
print(array['arr_0'])
print(array['arr_1'])
print(array['arr_2'])
print(array['arr_3'])
print(array['arr_4'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[0.5788873  0.69082947 0.04922545 0.86517602 0.29889969 0.55285575
 0.69389689 0.49183867 0.8308363  0.06454569]


In [49]:
#讀取並加入one_array.npy
npyone = np.load('one_array.npy')
#讀取並加入names.txt
txtfile = np.genfromtxt("names.txt", delimiter=",", names=True)
#讀取並加入test.csv
csvfile = np.genfromtxt("test.csv", delimiter=",")
with open('hw.npz', 'wb') as f:
    np.savez(f,array1,array2,npzmulti['array1'],npzmulti['array2'],npzmulti['array3'],npyone,txtfile,csvfile)

In [51]:
#讀取並加入test.gz
gzfile = np.genfromtxt("test.gz", delimiter=",")
#讀取並加入test.npy
npytest = np.load('test.npy')
#讀取並加入test.out
outfile = np.loadtxt('test.out', delimiter=',', dtype='f4')
#讀取並加入transform.txt
txtfile1 = np.genfromtxt("transform.txt", delimiter=',', dtype="i8, i8, U3, U3")
with open('hw.npz', 'wb') as f:
    np.savez(f,array1,array2,npzmulti['array1'],npzmulti['array2'],npzmulti['array3'],npyone,txtfile,csvfile,gzfile,npytest,outfile,txtfile1)

In [53]:
a = np.load('hw.npz')
print(a['arr_9'])
a.files

[1 2]


['arr_0',
 'arr_1',
 'arr_2',
 'arr_3',
 'arr_4',
 'arr_5',
 'arr_6',
 'arr_7',
 'arr_8',
 'arr_9',
 'arr_10',
 'arr_11']

In [63]:
print(a['arr_0'])
print(a['arr_1'])
print(a['arr_2'])
print(a['arr_3'])
print(a['arr_4'])
print(a['arr_5'])
print(a['arr_6'])
print(a['arr_7'])
print(a['arr_8'])
print(a['arr_9'])
print(a['arr_10'])
print(a['arr_11'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[0.5788873  0.69082947 0.04922545 0.86517602 0.29889969 0.55285575
 0.69389689 0.49183867 0.8308363  0.06454569]
[1 2]
[(1., 2., 3.) (4., 5., 6.) (7., 8., 9.)]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[0. 1. 2. 3. 4.]
[1 2]
[0. 1. 2. 3. 4.]
[(1, 2, 'Yes', '87%') (3, 4, 'No', '3%') (5, 6, 'Yes', '55%')]
